#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# Standalone Filebeat installer and config generator for Linux/WSL
# Usage: sudo bash install-filebeat.sh [--lab-root /path/to/elastic-lab]

LAB_ROOT="${1:-${SOC_LAB_ROOT:-$(pwd)/elastic-lab}}"
CONFIG_DIR="$LAB_ROOT/filebeat"

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "This installer supports Linux (WSL/native) only. For Windows, use the Winlogbeat script generated by the main installer." >&2
  exit 1
fi

if ! command -v apt-get >/dev/null 2>&1; then
  echo "apt-get not found. Please install Filebeat manually for your distribution." >&2
  exit 1
fi

set -x

# Prepare directories
mkdir -p "$CONFIG_DIR"

# Add Elastic APT repository
curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo apt-get update -y
sudo apt-get install -y apt-transport-https
sudo sh -c 'echo "deb https://artifacts.elastic.co/packages/9.x/apt stable main" > /etc/apt/sources.list.d/elastic-9.x.list'
sudo apt-get update -y

# Install Filebeat
sudo apt-get install -y filebeat

# Generate a near-real-time Filebeat config that tails logs and reads journald
cat > "$CONFIG_DIR/filebeat.yml" <<'EOF'
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/**/*.log
  tail_files: true
  scan_frequency: 1s

- type: journald
  enabled: true

filebeat.config.modules:
  path: /usr/share/filebeat/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "elastic"
  password: "<set_me_or_export_ELASTIC_PASSWORD>"
  protocol: https
  ssl.certificate_authorities: ["/etc/filebeat/certs/ca.crt"]

setup.template.enabled: true
setup.ilm.enabled: false
processors:
- add_host_metadata: ~
- add_cloud_metadata: ~
EOF

# Copy config into system location and preserve a backup
sudo cp /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.yml.orig 2>/dev/null || true
sudo cp "$CONFIG_DIR/filebeat.yml" /etc/filebeat/filebeat.yml

# Enable and start
sudo systemctl enable filebeat
sudo systemctl restart filebeat || sudo systemctl start filebeat

echo "Filebeat installed. Config placed at: $CONFIG_DIR/filebeat.yml and /etc/filebeat/filebeat.yml"
set +x
